import type { SessionController } from '../../src/composables/state';

export default function sessionControllerFixture(
  overrides: Partial<SessionController> = {},
): SessionController {
  return {
    key: 'controller-1',
    runtimeId: 'runtime-1',
    projectPath: '/tmp/project',
    sessionId: 'session-1',
    sessionPath: '/tmp/project/session.json',
    sessionName: '',
    phantom: false,
    generation: 0,
    ready: false,
    streaming: false,
    compacting: false,
    compactionReconciliationPending: false,
    compactionStreamSequence: 0,
    messagesHydrationSequence: 0,
    stopping: false,
    starting: false,
    working: false,
    promptSubmitting: false,
    unread: false,
    lastUserMessageAt: 0,
    hasPiTranscript: false,
    materializationVerified: false,
    materializationBarrierRequestId: '',
    postSettlementHydration: false,
    settledAssistantActivity: false,
    materializationStateRequestId: '',
    materializationMessagesRequestId: '',
    messages: [],
    messagesLoaded: false,
    historyLayers: [],
    firstVisibleHistoryLayer: 0,
    historyPrefixLength: 0,
    historyRequestId: '',
    localErrors: [],
    draft: '',
    retry: undefined,
    feedback: [],
    currentModelProvider: '',
    currentModelId: '',
    currentModelName: '',
    currentEffort: 'off',
    pendingEffort: '',
    pendingSettingRequestId: '',
    models: [],
    modelScope: [],
    efforts: [],
    commands: [],
    commandsLoaded: false,
    pendingPrompt: undefined,
    queue: { steering: [], followUp: [] },
    queueVersion: 0,
    queueSubmissions: [],
    queueSteeringMode: '',
    queueFollowUpMode: '',
    queuePreparing: false,
    queueClearing: false,
    queueFeedback: '',
    queueFailedDrafts: [],
    sessionNameRevision: 0,
    sessionNameStateRequestId: '',
    sessionNameStateRevision: 0,
    bootstrapStateRequestId: '',
    bootstrapSessionPath: '',
    runStateRequestId: '',
    startMessagesRequestId: '',
    commandPromptRequestId: '',
    commandSyncRequestId: '',
    replacementProbeRequestId: '',
    abortProbeRequestId: '',
    connectingRemote: false,
    remoteDisconnected: false,
    reconnectingRemote: false,
    remoteConnectionTimedOut: false,
    syncing: false,
    lastActiveSequence: 0,
    disposed: false,
    streamSequence: 0,
    ...overrides,
  };
}
